

                     SUMMARY OF PM3 CALCULATION, Site No: 1079

                                                       MOPAC2012 (Version: 15.146L)
                                                       Sat Dec 12 23:24:34 2015
                                                       No. of days left = 165

           Empirical Formula: H2 O  =     3 atoms

PM3 1SCF GRAD CHARGE=0 Singlet

 Mopac file generated by Gabedit


     1SCF WAS SPECIFIED, SO BFGS WAS NOT USED                 
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        -53.43282 KCAL/MOL =    -223.56293 KJ/MOL
          TOTAL ENERGY            =       -324.90736 EV
          ELECTRONIC ENERGY       =       -474.28723 EV
          CORE-CORE REPULSION     =        149.37987 EV
          GRADIENT NORM           =          0.14144
          DIPOLE                  =          1.73859 DEBYE    POINT GROUP:       C2v 
          NO. OF FILLED LEVELS    =          4
          IONIZATION POTENTIAL    =         12.316494 EV
          HOMO LUMO ENERGIES (EV) =        -12.316  4.059
          MOLECULAR WEIGHT        =         18.015
          COSMO AREA              =         42.47 SQUARE ANGSTROMS
          COSMO VOLUME            =         25.19 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H     3    H     2     1.53592
            H     2    O     1     0.56096
            O     1    H     2     0.00000
          SCF CALCULATIONS        =          1
          WALL-CLOCK TIME         =          0.016 SECONDS
          COMPUTATION TIME        =          0.010 SECONDS


          FINAL GEOMETRY OBTAINED
PM3 1SCF GRAD CHARGE=0 Singlet

 Mopac file generated by Gabedit
  O    -0.00001000 +1  -0.38096200 +1   0.00000000 +1
  H     0.76796600 +1   0.17999600 +1   0.00000000 +1
  H    -0.76792600 +1   0.17996400 +1  -0.01000000 +1
 
