#!/bin/bash
filename=$1 ; [ 0 = $# ] || shift

if [ -z "$filename" ]
then
   clear
   echo " "
   echo "Usage Exemple:"
   echo "       runG09 h2.com "
   echo "       fichier de donnees : h2.com"
   echo "==========================================="
   echo " "
   exit 1
fi
filecom=$filename
filename=${filecom%.com}


export g09root=/softs/CompChemPackages/Gaussian09D
. $g09root/g09/bsd/g09.profile

if [ -z "$PBS_JOBID" ]; then
export dtmp=${filename}
export GAUSS_SCRDIR=$dtmp
mkdir /tmp/$LOGNAME
else
export dtmp=${PBS_JOBID%.master0}
export GAUSS_SCRDIR=/scratch/$LOGNAME/$dtmp
mkdir /scratch/$LOGNAME
fi
export GAUSS_SCRDIR=$dtmp
mkdir $GAUSS_SCRDIR

echo Begin $filename
$g09root/g09/g09 <$filecom>$filename.log
echo End $filename
/bin/rm -r $GAUSS_SCRDIR

