#!/bin/bash
RUNMOLPRO=/home/allouche/bin/molpro
RUNMOLPRO=/home/allouche/Softwares/MolproTrial/molpro

filename=$1 ; [ 0 = $# ] || shift
outname=$1 ; [ 0 = $# ] || shift

if [ -z "$filename" ]
then
   clear
   echo " " 
   echo "==========================================="
   echo "                 runMolproHF "
   echo "-------------------------------------------"
   echo "Example:"
   echo "       runMolproHF h2.com h2.out"
   echo "==========================================="
   echo " " 
   exit 1
fi
filecom=$filename
filename=${filecom%.inp}
filename=${filename%.com}

DEFAULTDIR=`pwd`
if test ! -s "$filecom"
then
   echo " " 
   echo "============================================"
   echo " I cannot find $filecom file"
   echo "==============================================================================="
   echo " " 
   exit 2
fi

cd $DEFAULTDIR
#cat $filecom
fn=`echo "$filename" | sed "s/.*\///" | sed "s/\..*//"`
ffn=${fn}_$$
fn=${ffn}.com
echo $fn
echo ============== $filecom ===================
cat $filecom
echo "==============================================================================="

awk 'BEGIN{
natoms=0;
printf(" memory,64,m\n")
printf(" geomtyp=xyz\n")
}
{
i++;
#printf("i=%d s=%s\n",i,$1);

if(i==1) { option=$1 }
if(i==3) 
{ 
	natoms=$1
	charge=$2 
	mult=$3
	printf("set,charge=%d\n",charge)
	printf("set,spin=%d\n",mult-1)
	printf("! For recent molpro version, use :\n")
	printf("orient,nosym\n")
	printf("geometry={\n")
	printf(" %d ! number of atoms\n",natoms)
	printf("GeomXYZ\n")
}
if(i>3 && i<=natoms+3)
{
printf("%s %s %s %s\n",$1,$9,$10,$11);
if(i==natoms+3) printf("}\n")
}

}
END{
	printf("basis=cc-pvdz\n")
	printf("hf\n")
	if(option==2) printf(" optg\n")
	else if(option==1) printf(" forces\n")
}' $filecom > $fn
echo ============== $fn ===================
cat $fn
echo "==============================================================================="

filenameRes=${filename}_$$.out

$RUNMOLPRO $fn -o $filenameRes
tmpfile=${ffn}.tmp

# !RHF STATE 1.1 Energy                -76.027053512504
grep "STATE" $filenameRes | grep "Energy" >  ${ffn}.tmp

echo ============== ${ffn}.tmp ===================
cat ${ffn}.tmp
echo "==============================================================================="

energy=$(awk '{printf("%s",$5);}' $tmpfile)

# !RHF STATE 1.1 Dipole moment           0.00000000    -0.80425956     0.00000000
awk 'BEGIN{
id=0
}
{
	if($0 ~ /Dipole moment/) if($0 ~ /STATE/)
	{ 
		printf("%f\n%f\n%f\n",$6,$7,$8);
	}
}' $filenameRes > $tmpfile

read mux muy muz <<< $(cat $tmpfile | awk '{ print $1; }')
echo Mu = $mux $muy $muz
echo $outname
echo $energy >  $outname
echo $mux $muy $muz >>  $outname
echo 

# SCF GRADIENT FOR STATE 1.1
#
# Atom          dE/dx               dE/dy               dE/dz
#
#   1         0.000002872        -0.000003122         0.000000000
#   2        -0.000002872        -0.000003122         0.000000000
#   3         0.000000000         0.000006244         0.000000000

awk 'BEGIN{
id=0
iold=0
}
{
	if(id>=5) if(iold==0)
	{ 
		if(NF != 4) iold=1; 
		else printf("%f %f %f\n",$2,$3,$4);
	}  
	if(id>=1) id++;
	if($0 ~ /GRADIENT/) if($0 ~ /STATE/) { id=1;}
}' $filenameRes >>  $outname

echo ============== $outname ===================
cat $outname
echo "==============================================================================="

rm $tmpfile
rm $fn
rm $filenameRes

echo ============== $filenameRes ===================

