#!/bin/bash
RUNMOLPRO=/home/allouche/bin/molpro
molproVersion=2008

RUNMOLPRO=/home/allouche/Softwares/MolproTrial/molpro
molproVersion=2015


filename=$1 ; [ 0 = $# ] || shift
outname=$1 ; [ 0 = $# ] || shift

if [ -z "$filename" ]
then
   clear
   echo " " 
   echo "==========================================="
   echo "                 runMolproDFLMP2 "
   echo "-------------------------------------------"
   echo "Example:"
   echo "       runMolproDFLMP2 h2.com h2.out"
   echo "==========================================="
   echo " " 
   exit 1
fi
filecom=$filename
filename=${filecom%.inp}
filename=${filename%.com}

DEFAULTDIR=`pwd`
if test ! -s "$filecom"
then
   echo " " 
   echo "============================================"
   echo " I cannot find $filecom file"
   echo "==============================================================================="
   echo " " 
   exit 2
fi

cd $DEFAULTDIR
#cat $filecom
fn=`echo "$filename" | sed "s/.*\///" | sed "s/\..*//"`
ffn=${fn}_$$
fn=${ffn}.com
tmpfile=${ffn}_tmp.txt
#echo $fn
#echo ============== $filecom ===================
#cat $filecom
#echo "==============================================================================="

awk -v molproVersion=$molproVersion 'BEGIN{
natoms=0;
printf(" memory,64,m\n")
printf(" geomtyp=xyz\n")
}
{
i++;
#printf("i=%d s=%s\n",i,$1);

if(i==1) { option=$1 }
if(i==3) 
{ 
	natoms=$1
	charge=$2 
	mult=$3
	printf("set,charge=%d\n",charge)
	printf("set,spin=%d\n",mult-1)
	if(molproVersion>=2009) printf("symmetry,nosym\n");
	printf("geometry={\n")
	if(molproVersion<=2008) printf("nosym,\n");
	printf(" %d ! number of atoms\n",natoms)
	printf("GeomXYZ\n")
}
if(i>3 && i<=natoms+3)
{
printf("%s %s %s %s\n",$1,$9,$10,$11);
if(i==natoms+3) printf("}\n")
}

}
END{
	printf("basis=avtz\n")
	printf("{df-hf,basis=avtz}\n")
	printf("{df-lmp2,basis=avtz;polari,dm}\n")
	if(option==2) printf(" optg\n")
	else if(option==1) printf(" forces\n")
}' $filecom > $fn
echo "{table,energy;head,' ';format,(f30.14);save,$tmpfile,new;}" >> $fn
echo "{table,dmx(1);head,' ';format,(f30.14);save,$tmpfile;}" >> $fn
echo "{table,dmy(1);head,' ';format,(f30.14);save,$tmpfile;}" >> $fn
echo "{table,dmz(1);head,' ';format,(f30.14);save,$tmpfile;}" >> $fn
#echo ============== $fn ===================
#cat $fn
#echo "==============================================================================="

filenameRes=${filename}_$$.out

$RUNMOLPRO $fn -o $filenameRes
# the name of printed file by Molpro by table keyword is always in lowercase
sl=${tmpfile,,}
mv $sl $tmpfile 
#echo ============== ${tmpfile} ===================
#cat ${tmpfile}
#echo "==============================================================================="
read energy mux muy muz <<< $(cat $tmpfile | awk '{ print $1; }')


#echo energy = $energy
#echo Mu = $mux $muy $muz
#echo $outname

echo $energy >  $outname
echo $mux $muy $muz >>  $outname

# SCF GRADIENT FOR STATE 1.1
#
# Atom          dE/dx               dE/dy               dE/dz
#
#   1         0.000002872        -0.000003122         0.000000000
#   2        -0.000002872        -0.000003122         0.000000000
#   3         0.000000000         0.000006244         0.000000000

awk 'BEGIN{
id=0
iold=0
}
{
	if(id>=5) if(iold==0)
	{ 
		if(NF != 4) iold=1; 
		else printf("%s %s %s\n",$2,$3,$4);
	}  
	if(id>=1) id++;
	if($0 ~ /GRADIENT/) if($0 ~ /STATE/) { id=1;}
}' $filenameRes >>  $outname

#echo ============== $outname ===================
#cat $outname
#echo "==============================================================================="

rm $tmpfile
rm $fn
rm $filenameRes

#echo ============== $filenameRes ===================
#
