#!/bin/bash
fileinp=$1 ; [ 0 = $# ] || shift

if [ -z "$fileinp" ]
then
   clear
   echo " " 
   echo "Usage Exemple:"
   echo "       runOrca h2.inp "
   echo "       fichier de donnees : h2.inp"
   echo "==========================================="
   echo " " 
   exit 1
fi

filename=${fileinp%.inp}
filename=${filename%.com}
filename=${filename%.ici}

DEFAULTDIR=`pwd`
export OMP_NUM_THREADS=1
export ORCATMP=/tmp/$USER/$RANDOM
mkdir /tmp/$USER
mkdir $ORCATMP
#module load gcc/4.7.3 openmpi/1.7.4/openmpi-gcc47
echo Begin $filename
cp  $fileinp  $ORCATMP/input.inp
cd  $ORCATMP
#cat input.inp
#~/Softwares/orca_3_0_2_linux_x86-64/orca input.inp > $filename.out
/home/allouche/Softwares/orca_4_1_2_linux_x86-64_openmpi313/orca input.inp > $filename.out
cat input.engrad >> $filename.out
cp input.hess  $DEFAULTDIR/$filename.hess
cp $filename.out $DEFAULTDIR/.
cd $DEFAULTDIR
cat $filename.hess >> $filename.out
echo End $filename
#cat $filename.out

/bin/rm -r $ORCATMP
