

                     SUMMARY OF PM6 CALCULATION, Site No: 1079

                                                       MOPAC2012 (Version: 15.146L)
                                                       Sat Dec 19 17:54:50 2015
                                                       No. of days left = 158

           Empirical Formula: C6 H14 N O5  =    26 atoms

PM6 GNORM=0.001 XYZ CHARGE=1 Singlet

 Mopac file generated by Gabedit


     GEOMETRY OPTIMISED USING EIGENVECTOR FOLLOWING (EF).     
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        794.00917 KCAL/MOL =    3322.13435 KJ/MOL
          TOTAL ENERGY            =      -2518.73068 EV
          ELECTRONIC ENERGY       =     -12313.26941 EV
          CORE-CORE REPULSION     =       9794.53873 EV
          GRADIENT NORM           =        136.00742
          DIPOLE                  =         36.45086 DEBYE    POINT GROUP:       C1  
          NO. OF FILLED LEVELS    =         36
          CHARGE ON SYSTEM        =          1
          IONIZATION POTENTIAL    =          6.614582 EV
          HOMO LUMO ENERGIES (EV) =         -6.615 -5.229
          MOLECULAR WEIGHT        =        180.180
          COSMO AREA              =        351.57 SQUARE ANGSTROMS
          COSMO VOLUME            =        307.95 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H    17    H    19    12.88903
            H    21    N     6    11.17277
            H    18    H    15     7.90721
          SCF CALCULATIONS        =         50
          WALL-CLOCK TIME         =         17.281 SECONDS
          COMPUTATION TIME        =  4 MINUTES AND 35.653 SECONDS


          FINAL GEOMETRY OBTAINED
PM6 GNORM=0.001 XYZ CHARGE=1 Singlet

 Mopac file generated by Gabedit
  C     1.11654162 +1  -0.96250880 +1   1.34024407 +1
  O    -0.23309786 +1   0.40352881 +1  -0.30285753 +1
  C    -1.75975287 +1   1.92123790 +1   0.67732189 +1
  O    -2.71151346 +1   1.51052219 +1   0.19343881 +1
  C    -0.99683912 +1  -1.70535411 +1   0.74206680 +1
  N    -1.91691520 +1  -0.72703913 +1  -2.37783760 +1
  C    -0.52715008 +1  -0.99889073 +1  -0.45515813 +1
  O    -1.12021378 +1  -1.35402511 +1  -1.87440517 +1
  C     0.88948613 +1  -0.51144265 +1  -0.14237040 +1
  O     0.09652354 +1  -1.65315084 +1   1.62373928 +1
  C     1.84613569 +1   2.79700068 +1  -0.26249517 +1
  O     1.94086321 +1  -0.39206300 +1  -0.99290924 +1
  H     0.75577193 +1   4.01767005 +1   3.45362459 +1
  H     3.18184474 +1   3.47797244 +1   1.86564396 +1
  H     0.26368060 +1   4.61286840 +1   3.40361513 +1
  H     1.06079116 +1   3.41396120 +1   0.15986059 +1
  H    -3.45537378 +1   1.69324948 +1   5.78336138 +1
  H     6.30379929 +1  -2.69150312 +1   4.30641101 +1
  H     7.86704051 +1   2.94878678 +1  -0.24604677 +1
  H     1.51145611 +1  -1.69388434 +1   4.92015187 +1
  H     5.86073906 +1   0.07193526 +1   6.12511485 +1
  H     8.07367151 +1   2.10679613 +1  -0.10051390 +1
  H     2.02616212 +1   0.55352939 +1  -1.36961703 +1
  H     7.18988150 +1   2.33970040 +1  -0.16254825 +1
  H     2.34578862 +1   3.24783105 +1  -1.16318536 +1
  H     2.46929595 +1   3.71983335 +1   1.55480026 +1
 
