

                     SUMMARY OF PM7 CALCULATION, Site No: 1079

                                                       MOPAC2012 (Version: 15.146L)
                                                       Sat Dec 19 19:36:05 2015
                                                       No. of days left = 158

           Empirical Formula: C6 H14 N O5  =    26 atoms

PM7 GNORM=0.001 XYZ CHARGE=1 Singlet

 Mopac file generated by Gabedit


     GEOMETRY OPTIMISED USING EIGENVECTOR FOLLOWING (EF).     
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        -88.34121 KCAL/MOL =    -369.61961 KJ/MOL
          TOTAL ENERGY            =      -2582.83378 EV
          ELECTRONIC ENERGY       =     -14772.15773 EV
          CORE-CORE REPULSION     =      12189.32395 EV
          GRADIENT NORM           =          0.08707
          DIPOLE                  =          3.40547 DEBYE    POINT GROUP:       C1  
          NO. OF FILLED LEVELS    =         36
          CHARGE ON SYSTEM        =          1
          IONIZATION POTENTIAL    =         14.219105 EV
          HOMO LUMO ENERGIES (EV) =        -14.219 -3.311
          MOLECULAR WEIGHT        =        180.180
          COSMO AREA              =        184.68 SQUARE ANGSTROMS
          COSMO VOLUME            =        195.94 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H    16    H    24     6.07806
            H    26    H    21     5.72047
            H    15    H    18     4.69385
          SCF CALCULATIONS        =        144
          WALL-CLOCK TIME         =          2.070 SECONDS
          COMPUTATION TIME        =         31.642 SECONDS


          FINAL GEOMETRY OBTAINED
PM7 GNORM=0.001 XYZ CHARGE=1 Singlet

 Mopac file generated by Gabedit
  C     1.11246594 +1   0.61823635 +1   0.68944385 +1
  O    -0.07606200 +1   1.26393321 +1   0.23769569 +1
  C    -1.24675443 +1   0.69934703 +1   0.78814801 +1
  O    -2.29489458 +1   1.55259232 +1   0.43181051 +1
  C    -1.53923211 +1  -0.62950117 +1   0.03557928 +1
  N    -2.13743419 +1  -0.27889361 +1  -1.31754323 +1
  C    -0.21128283 +1  -1.41436223 +1  -0.20591605 +1
  O     0.09911549 +1  -1.26004386 +1  -1.56110753 +1
  C     0.92469391 +1  -0.91536043 +1   0.71873431 +1
  O     0.46541009 +1  -1.20662391 +1   2.02181148 +1
  C     2.19921280 +1   1.11699623 +1  -0.26986942 +1
  O     2.37141481 +1   0.11761226 +1  -1.26182205 +1
  H     1.30818860 +1   0.99133380 +1   1.72968509 +1
  H    -1.18149813 +1   0.58828957 +1   1.89403103 +1
  H    -2.07235171 +1   2.50223122 +1   0.60353101 +1
  H    -2.26537147 +1  -1.24944474 +1   0.61881963 +1
  H    -2.29015113 +1  -1.13045577 +1  -1.88095349 +1
  H    -0.37551544 +1  -2.51139038 +1  -0.06475680 +1
  H     0.94687722 +1  -0.73564209 +1  -1.67792036 +1
  H     1.87844030 +1  -1.44479817 +1   0.48768502 +1
  H     1.06155537 +1  -1.82667512 +1   2.49687534 +1
  H     3.17061234 +1   1.24669051 +1   0.24985801 +1
  H     1.89673874 +1   2.06957838 +1  -0.75237620 +1
  H     2.96837733 +1   0.42336925 +1  -1.97972262 +1
  H    -1.45582507 +1   0.32368629 +1  -1.82261242 +1
  H    -3.02099967 +1   0.24648376 +1  -1.19451768 +1
 
