

                     SUMMARY OF PM7 CALCULATION, Site No: 1079

                                                       MOPAC2012 (Version: 15.146L)
                                                       Sat Dec 19 19:35:00 2015
                                                       No. of days left = 158

           Empirical Formula: C6 H14 N O5  =    26 atoms

PM7 1SCF GRAD CHARGE=1 Singlet

 Mopac file generated by Gabedit


     1SCF WAS SPECIFIED, SO BFGS WAS NOT USED                 
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        -85.77608 KCAL/MOL =    -358.88713 KJ/MOL
          TOTAL ENERGY            =      -2582.73976 EV
          ELECTRONIC ENERGY       =     -14773.31148 EV
          CORE-CORE REPULSION     =      12190.57172 EV
          GRADIENT NORM           =         47.20581
          DIPOLE                  =          3.02035 DEBYE    POINT GROUP:       C1  
          NO. OF FILLED LEVELS    =         36
          CHARGE ON SYSTEM        =          1
          IONIZATION POTENTIAL    =         14.157426 EV
          HOMO LUMO ENERGIES (EV) =        -14.157 -3.331
          MOLECULAR WEIGHT        =        180.180
          COSMO AREA              =        185.12 SQUARE ANGSTROMS
          COSMO VOLUME            =        195.81 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H    26    H    24     6.23189
            H    18    H    15     5.08861
            H    25    H    21     4.84202
          SCF CALCULATIONS        =          1
          WALL-CLOCK TIME         =          0.055 SECONDS
          COMPUTATION TIME        =          0.514 SECONDS


          FINAL GEOMETRY OBTAINED
PM7 1SCF GRAD CHARGE=1 Singlet

 Mopac file generated by Gabedit
  C     1.12015800 +1   0.61373200 +1   0.70641900 +1
  O    -0.04088200 +1   1.23221400 +1   0.19127400 +1
  C    -1.23289500 +1   0.72358100 +1   0.75234800 +1
  O    -2.27350200 +1   1.58831100 +1   0.41499000 +1
  C    -1.53848900 +1  -0.63630200 +1   0.06333300 +1
  N    -2.21336900 +1  -0.36678700 +1  -1.26943200 +1
  C    -0.22080700 +1  -1.39899100 +1  -0.22548800 +1
  O     0.08262600 +1  -1.15080300 +1  -1.57559000 +1
  C     0.90846500 +1  -0.92474400 +1   0.71082500 +1
  O     0.42637900 +1  -1.28914100 +1   1.97908800 +1
  C     2.21091700 +1   1.13041700 +1  -0.24978400 +1
  O     2.43708700 +1   0.12959500 +1  -1.22815800 +1
  H     1.33106900 +1   0.95441600 +1   1.73533000 +1
  H    -1.16006200 +1   0.63651400 +1   1.84770400 +1
  H    -2.01617000 +1   2.54604200 +1   0.53950000 +1
  H    -2.21429500 +1  -1.24459500 +1   0.69618000 +1
  H    -2.49291300 +1  -1.21174400 +1  -1.76320600 +1
  H    -0.37825800 +1  -2.48520000 +1  -0.12519400 +1
  H     1.01016700 +1  -0.79536900 +1  -1.68001400 +1
  H     1.85812900 +1  -1.44314600 +1   0.49383000 +1
  H     1.09335000 +1  -1.71218200 +1   2.55452800 +1
  H     3.17119800 +1   1.30769300 +1   0.27416600 +1
  H     1.84278300 +1   2.03731200 +1  -0.78767000 +1
  H     3.15860800 +1   0.39190500 +1  -1.83155500 +1
  H    -1.51424600 +1   0.14891900 +1  -1.86494600 +1
  H    -3.03254000 +1   0.25966300 +1  -1.13249800 +1
 
