#!/bin/bash
echo " Begin QFF2MR-VPT2 calculation">  $0.log
CCHEMI=/home/theochem/allouche/bin/cchemi
# Opt+ Freq => h2oFreq.gab
#$CCHEMI h2o.ici
#remove the 6 first modes , manually

# generate QFF energies files
/bin/rm -f h2oVQFF_*.ici
/bin/rm -f h2oVQFF_*.gab
$CCHEMI h2oV.ici >> $0.log 2>  $0.err
ls h2oVQFF_* > xp
sed -i 's/h2oVQFF/runCChemI h2oVQFF/' xp
#cat xp
chmod u+x xp
./xp >>  $0.log 2>> $0.err
sed -i 's/RunType=GenerateQFF2MRFiles/#RunType=GenerateQFF2MRFiles/g' h2oV.ici
sed -i 's/#RunType=ComputeQFF2MRFromFiles/RunType=ComputeQFF2MRFromFiles/g' h2oV.ici

# generate txt data for VPT2 calculation
$CCHEMI h2oV.ici  >>  $0.log 2>> $0.err

sed -i 's/#RunType=GenerateQFF2MRFiles/RunType=GenerateQFF2MRFiles/g' h2oV.ici
sed -i 's/RunType=ComputeQFF2MRFromFiles/#RunType=ComputeQFF2MRFromFiles/g' h2oV.ici

# make ici  file for VPT2 calculation
echo 'RunType=VPT2' > h2oVQFF.ici
cat h2oVQFF.txt >> h2oVQFF.ici

# generate txt data for VPT2 calculation
$CCHEMI h2oVQFF.ici  >  $0.out 2>> $0.err


/bin/rm xp
/bin/rm h2oVQFF_*.ici
/bin/rm h2oVQFF_*.gab
echo "==========================================================================="
echo "See $0.out , $0.log and $0.err files "
echo "==========================================================================="
