

                     SUMMARY OF PM3 CALCULATION, Site No: 1079

                                                       MOPAC2012 (Version: 15.146L)
                                                       Sun Dec 13 17:09:22 2015
                                                       No. of days left = 164

           Empirical Formula: H2 O  =     3 atoms

PM3 1SCF CHARGE=0 Singlet

 Mopac file generated by Gabedit


     1SCF WAS SPECIFIED, SO BFGS WAS NOT USED                 
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        -37.19905 KCAL/MOL =    -155.64081 KJ/MOL
          TOTAL ENERGY            =       -324.20339 EV
          ELECTRONIC ENERGY       =       -478.05101 EV
          CORE-CORE REPULSION     =        153.84762 EV
          DIPOLE                  =          1.72175 DEBYE    POINT GROUP:       Cs  
          NO. OF FILLED LEVELS    =          4
          IONIZATION POTENTIAL    =         12.336209 EV
          HOMO LUMO ENERGIES (EV) =        -12.336  3.890
          MOLECULAR WEIGHT        =         18.015
          COSMO AREA              =         41.96 SQUARE ANGSTROMS
          COSMO VOLUME            =         24.80 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H     3    H     2     1.48578
            H     2    O     1     0.53472
            H     2    H     3     0.00000
          SCF CALCULATIONS        =          1
          WALL-CLOCK TIME         =          0.016 SECONDS
          COMPUTATION TIME        =          0.011 SECONDS


          FINAL GEOMETRY OBTAINED
PM3 1SCF CHARGE=0 Singlet

 Mopac file generated by Gabedit
  O    -0.00966800 +1  -0.37893000 +1   0.00000000 +1
  H     0.81743200 +1   0.21983400 +1  -0.00000300 +1
  H    -0.66411800 +1   0.10784900 +1   0.00000600 +1
 
