#P B3LYP/6-31G* scf=tight   nosym Opt(Z-matrix) Freq
#  Units(Ang,Deg)

File generated by Gabedit
Quantum Mechanics Energy(kCal/mol) = -681.565865

0 1
Al -0.081971 0.722098 1.193123
O -0.279838 -1.034810 -2.829948
Al -0.205123 -0.371403 -1.310839
O -0.390492 1.126549 -0.415609
O 0.107231 -0.741813 0.375841

