#P B3LYP/6-31G* scf=tight   nosym Opt(Z-matrix) Freq
#  Units(Ang,Deg)

File generated by Gabedit
Quantum Mechanics Energy(kCal/mol) = -655.256305

0 1
Al 1.995042 0.823684 -2.294180
O -1.026168 -0.182460 0.762278
Al 0.626815 0.124391 0.671616
O 1.343522 0.490696 -0.881932
O 1.606509 0.087128 2.040390

