

                     SUMMARY OF PM6 CALCULATION, Site No: 1079

                                                       MOPAC2012 (Version: 14.142L)
                                                       Tue Mar  3 18:12:48 2015
                                                       No. of days left =  80

           Empirical Formula: H2 O  =     3 atoms

PM6 CHARGE=0 Singlet

 Mopac file generated by CChemI


     GEOMETRY OPTIMISED USING EIGENVECTOR FOLLOWING (EF).     
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        -54.30617 KCAL/MOL =    -227.21699 KJ/MOL
          TOTAL ENERGY            =       -319.07752 EV
          ELECTRONIC ENERGY       =       -458.35418 EV
          CORE-CORE REPULSION     =        139.27666 EV
          GRADIENT NORM           =          0.55417
          DIPOLE                  =          2.06890 DEBYE    POINT GROUP:       C2v 
          NO. OF FILLED LEVELS    =          4
          IONIZATION POTENTIAL    =         11.903147 EV
          HOMO LUMO ENERGIES (EV) =        -11.903  4.064
          MOLECULAR WEIGHT        =         18.015
          COSMO AREA              =         42.45 SQUARE ANGSTROMS
          COSMO VOLUME            =         25.16 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H     2    H     1     1.53182
            O     3    H     2     0.56096
            H     1    H     2     0.00000
          SCF CALCULATIONS        =          5
          WALL-CLOCK TIME         =          0.055 SECONDS
          COMPUTATION TIME        =          0.016 SECONDS


          FINAL GEOMETRY OBTAINED
* ===============================
* Input file for Mopac
* MM/SE Energy(kCal/mol) =0.000000
* ===============================
PM6 CHARGE=0 Singlet

 Mopac file generated by CChemI
  H     0.93223430 +1  -0.31572630 +1  -0.28649777 +1
  H     0.40770242 +1   1.06944976 +1  -0.67715816 +1
  O     0.53733372 +1   0.47817352 +1   0.05372952 +1
 
