

                     SUMMARY OF  PM3 CALCULATION, Site No: 1079

                                                       MOPAC2016 (Version: 19.338L)
                                                       Wed Mar  4 14:24:08 2020

           Empirical Formula: H2 O  =     3 atoms

 XYZ PM3 CHARGE=0 Singlet

 Mopac file generated by Gabedit


     GEOMETRY OPTIMISED USING EIGENVECTOR FOLLOWING (EF).     
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        -53.43270 KCAL/MOL =    -223.56244 KJ/MOL
          TOTAL ENERGY            =       -324.90735 EV
          ELECTRONIC ENERGY       =       -474.27017 EV
          CORE-CORE REPULSION     =        149.36281 EV
          GRADIENT NORM           =          0.65392 = 0.37754 PER ATOM
          DIPOLE                  =          1.73865 DEBYE    POINT GROUP:       C2v 
          NO. OF FILLED LEVELS    =          4
          IONIZATION POTENTIAL    =         12.316182 EV
          HOMO LUMO ENERGIES (EV) =        -12.316  4.058
          MOLECULAR WEIGHT        =         18.0152
          COSMO AREA              =         42.43 SQUARE ANGSTROMS
          COSMO VOLUME            =         25.15 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H     2    H     1     1.53633
            O     3    H     1     0.56094
            H     1    H     2     0.00000
          SCF CALCULATIONS        =         11
          WALL-CLOCK TIME         =          0.160 SECONDS
          COMPUTATION TIME        =          0.024 SECONDS


          FINAL GEOMETRY OBTAINED
 XYZ PM3 CHARGE=0 Singlet

 Mopac file generated by Gabedit
  H     0.00000000 +1   0.77870127 +1  -0.44376571 +1
  H     0.00000000 +1  -0.75754023 +1  -0.46039647 +1
  O    -0.00000000 +1   0.00472840 +1   0.10883062 +1
 
