

                     SUMMARY OF PM6 CALCULATION, Site No: 1079

                                                       MOPAC2012 (Version: 14.142L)
                                                       Tue Mar  3 18:51:50 2015
                                                       No. of days left =  80

           Empirical Formula: H2 O Li  =     4 atoms

XYZ PM6 CHARGE=1 Singlet

 Mopac file generated by Gabedit


     GEOMETRY OPTIMISED USING EIGENVECTOR FOLLOWING (EF).     
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =         70.89672 KCAL/MOL =     296.63188 KJ/MOL
          TOTAL ENERGY            =       -320.02373 EV
          ELECTRONIC ENERGY       =       -503.74075 EV
          CORE-CORE REPULSION     =        183.71702 EV
          GRADIENT NORM           =          0.70381
          DIPOLE                  =          4.39131 DEBYE    POINT GROUP:       C2v 
          NO. OF FILLED LEVELS    =          4
          CHARGE ON SYSTEM        =          1
          IONIZATION POTENTIAL    =         17.995499 EV
          HOMO LUMO ENERGIES (EV) =        -17.995 -3.504
          MOLECULAR WEIGHT        =         24.955
          COSMO AREA              =         77.09 SQUARE ANGSTROMS
          COSMO VOLUME            =         58.46 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
           Li     4    H     2     2.74433
            H     2    H     1     1.48285
            O     3    H     1     0.00052
          SCF CALCULATIONS        =         14
          WALL-CLOCK TIME         =          0.031 SECONDS
          COMPUTATION TIME        =          0.016 SECONDS


          FINAL GEOMETRY OBTAINED
XYZ PM6 CHARGE=1 Singlet

 Mopac file generated by Gabedit
  H     0.72691989 +1  -0.42076013 +1  -0.73838839 +1
  H     0.20230583 +1   1.02468347 +1  -0.89433357 +1
  O     0.49799248 +1   0.37592548 +1  -0.24229984 +1
 Li     0.61426250 +1   0.63635018 +1   1.79096929 +1
 
