#!/bin/bash

ener=$1

sortEner=sortEner$$

#echo "Sorting of energies "
sort -n -k1 $ener > $sortEner
#echo "End Sorting of energies "

emax=$(tail -1 $sortEner | awk '{printf("%s",$1);}')
emin=$(head -1 $sortEner | awk '{printf("%s",$1);}')
nhist=100

awk -v emin=$emin -v emax=$emax -v nhist=$nhist  'BEGIN{
pas=(emax-emin)/(nhist-1)
for(i=0;i<nhist;i++) H[i]=0
for(i=0;i<nhist;i++) Em[i]=-0
for(i=0;i<nhist;i++) fn[i]="Noting"
}
{
 ii=int(($1-emin)/pas)
#  printf("%f %d\n",$1,ii);
 if(H[ii]==0 || $1<=Em[ii]){ 
	Em[ii]=$1; 
	fn[ii]=$2;
	for(k=3;k<=NF;k++) 
		if(k==3) fn[ii]=fn[ii]"\t"$k;
		else fn[ii]=fn[ii]" "$k;
	}
# else if($1<=Em[ii]) { Em[ii]=$1; fn[ii]=fn[ii]", "$2;}
 H[ii]++;
}
END{

nAll=0; for(i=0;i<nhist;i++) nAll+=H[i]; 

printf("%-14s %-6s %-14s %-20s %s\n","#x", "H", "per cent","Emin","Comment");
for(i=0;i<nhist;i++) printf("%-14.8f %-6.0f %-14.4f %-20.10f %s\n",emin+i*pas, H[i], H[i]*1.0/nAll*100,Em[i],fn[i]);

printf("#pas=%f\n",pas);
nAll=0; for(i=0;i<nhist;i++) nAll+=H[i]; printf("#nAll=%d\n",nAll);

}' $sortEner

rm $sortEner


exit


