

                     SUMMARY OF PM6 CALCULATION, Site No: 1079

                                                       MOPAC2016 (Version: 17.163L)
                                                       Fri Jun  1 14:40:03 2018
                                                       No. of days remaining =  11

           Empirical Formula: H5 N O  =     7 atoms

PM6 GNORM=0.001 XYZ UHF CHARGE=0 Triplet

 Mopac file generated by Gabedit


     GEOMETRY OPTIMISED USING EIGENVECTOR FOLLOWING (EF).     
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =         24.68430 KCAL/MOL =     103.27910 KJ/MOL
          TOTAL ENERGY            =       -536.02270 EV
          ELECTRONIC ENERGY       =      -1116.16133 EV
          CORE-CORE REPULSION     =        580.13863 EV
          GRADIENT NORM           =          0.06199
          DIPOLE                  =          5.36310 DEBYE    POINT GROUP:       Cs  
          (SZ)                    =          1.000000
          (S**2)                  =          2.013720
          NO. OF ALPHA ELECTRONS  =          9
          NO. OF BETA  ELECTRONS  =          7
          IONIZATION POTENTIAL    =          7.577118 EV
          ALPHA SOMO LUMO (EV)    =         -7.577  3.256
          BETA  SOMO LUMO (EV)    =        -10.113 -0.819
          MOLECULAR WEIGHT        =         35.0456
          COSMO AREA              =         81.61 SQUARE ANGSTROMS
          COSMO VOLUME            =         55.68 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H     6    H     3     4.67884
            H     3    H     7     1.60659
            H     3    O     1     0.06092
          SCF CALCULATIONS        =        130
          WALL-CLOCK TIME         =          0.137 SECONDS
          COMPUTATION TIME        =          0.140 SECONDS


          FINAL GEOMETRY OBTAINED
PM6 GNORM=0.001 XYZ UHF CHARGE=0 Triplet

 Mopac file generated by Gabedit
  O     0.67621976 +1  -1.05617698 +1   0.17399899 +1
  H     1.44866558 +1  -0.44195251 +1   0.62681043 +1
  H    -0.05206885 +1  -1.03075135 +1   0.77151181 +1
  N     3.52556529 +1   0.69056881 +1   0.91047500 +1
  H     2.28290869 +1   0.13508780 +1   0.95843946 +1
  H     3.94809441 +1   1.23733377 +1   1.63525719 +1
  H     4.11721264 +1   0.57787324 +1   0.11007452 +1
 
