

                     SUMMARY OF PM7 CALCULATION, Site No: 1079

                                                       MOPAC2012 (Version: 15.146L)
                                                       Mon Feb 15 16:39:12 2016
                                                       No. of days left = 100

           Empirical Formula: H2 O  =     3 atoms

PM7 1SCF GRAD CHARGE=0 Singlet

 Mopac file generated by Gabedit


     1SCF WAS SPECIFIED, SO BFGS WAS NOT USED                 
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        157.98325 KCAL/MOL =     661.00190 KJ/MOL
          TOTAL ENERGY            =       -313.32189 EV
          ELECTRONIC ENERGY       =       -402.93276 EV
          CORE-CORE REPULSION     =         89.61087 EV
          GRADIENT NORM           =        245.94408
          DIPOLE                  =          3.47304 DEBYE    POINT GROUP:       C2v 
          NO. OF FILLED LEVELS    =          4
          IONIZATION POTENTIAL    =          9.315872 EV
          HOMO LUMO ENERGIES (EV) =         -9.316 -0.277
          MOLECULAR WEIGHT        =         18.015
          COSMO AREA              =         56.18 SQUARE ANGSTROMS
          COSMO VOLUME            =         34.69 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H     3    H     2     2.96784
            H     2    O     1     1.00825
            O     1    H     2     0.00000
          SCF CALCULATIONS        =          1
          WALL-CLOCK TIME         =          0.016 SECONDS
          COMPUTATION TIME        =          0.016 SECONDS


          FINAL GEOMETRY OBTAINED
PM7 1SCF GRAD CHARGE=0 Singlet

 Mopac file generated by Gabedit
  O     0.00000000 +1   0.00000000 +1   0.20165100 +1
  H     0.00000000 +1   1.48392000 +1  -0.80660200 +1
  H     0.00000000 +1  -1.48392000 +1  -0.80660200 +1
 
