#!/bin/bash
filename=$1 ; [ 0 = $# ] || shift

if [ -z "$filename" ]
then
   clear
   echo " " 
   echo "Usage Exemple:"
   echo "       runOrca h2.inp "
   echo "       fichier de donnees : h2.inp"
   echo "==========================================="
   echo " " 
   exit 1
fi
fileinp=$filename
filename=${fileinp%.inp}
filename=${filename%.com}

DEFAULTDIR=`pwd`
cpid=$$
export ORCATMP=/tmp/$LOGNAME/orca${SLURM_JOBID}_${cpid}
mkdir /tmp/$LOGNAME
mkdir $ORCATMP

module load gcc/4.7.3 openmpi/1.7.4/openmpi-gcc47
echo Begin $filename
cp  $fileinp  $ORCATMP/input.inp
cd  $ORCATMP
/home_nfs/ilm/allouche/Softwares/orca_3_0_2_linux_x86-64/orca input.inp > $filename.out
if [[ $filename == *"/"* ]]
then
echo "filename=$filename"
cat input.hess >>  $filename.out
cat input.engrad >>  $filename.out
else
cat input.hess >>  $filename.out
cat input.engrad >>  $filename.out
cp $filename.out $DEFAULTDIR/$filename.out
fi
cd $DEFAULTDIR
echo End $filename

/bin/rm -r $ORCATMP
