

                     SUMMARY OF PM3 CALCULATION, Site No: 1079

                                                       MOPAC2016 (Version: 16.158L)
                                                       Sun Jul 10 17:26:20 2016
                                                       No. of days remaining = 332

           Empirical Formula: H2 O  =     3 atoms

PM3 1SCF CHARGE=0 Singlet

 Mopac file generated by Gabedit


     1SCF WAS SPECIFIED, SO BFGS WAS NOT USED                 
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        -53.23904 KCAL/MOL =    -222.75214 KJ/MOL
          TOTAL ENERGY            =       -324.89896 EV
          ELECTRONIC ENERGY       =       -473.60152 EV
          CORE-CORE REPULSION     =        148.70256 EV
          DIPOLE                  =          1.76138 DEBYE    POINT GROUP:       C2v 
          NO. OF FILLED LEVELS    =          4
          IONIZATION POTENTIAL    =         12.331577 EV
          HOMO LUMO ENERGIES (EV) =        -12.332  4.065
          MOLECULAR WEIGHT        =         18.0152
          COSMO AREA              =         42.47 SQUARE ANGSTROMS
          COSMO VOLUME            =         25.21 CUBIC ANGSTROMS

          MOLECULAR DIMENSIONS (Angstroms)

            Atom       Atom       Distance
            H     2    H     1     1.51752
            O     3    H     1     0.58597
            O     3    H     1     0.00000
          SCF CALCULATIONS        =          1
          WALL-CLOCK TIME         =          0.016 SECONDS
          COMPUTATION TIME        =          0.016 SECONDS


          FINAL GEOMETRY OBTAINED
PM3 1SCF CHARGE=0 Singlet

 Mopac file generated by Gabedit
  H     0.04296800 +1  -0.89693600 +1  -0.20053500 +1
  H    -0.42108000 +1   0.46953800 +1  -0.66986400 +1
  O     0.02382200 +1   0.02692800 +1   0.05483900 +1
 
