#!/bin/bash
echo "IGVPT2BIN = $IGVPT2BIN"
fileici=$1 ; [ 0 = $# ] || shift
if [ -z "$fileici" ]
then
   clear
   echo " " 
   echo "================================"
   echo "Usage Exemple: runiGVPT2 h2.ici "
   echo "================================"
   echo " " 
   exit 1
fi

if [ -z "$JOB_ID" ]
then
export JID=$RANDOM
else
export JID=$SLURM_JOBID
fi

if [ -z "$TMPDIR" ]
then
export TMPDIR=/tmp
fi

export OMP_NUM_THREADS=1
filename=${fileici%.ici}
DEFAULTDIR=`pwd`
export  LOG=$DEFAULTDIR/$filename.log
export IGVPT2TMP=$TMPDIR/cchemi_${JID}_${filename}
mkdir $IGVPT2TMP
cd $IGVPT2TMP
cp $DEFAULTDIR/$fileici .
echo "run $fileici ......"
echo "===================" > $LOG
echo "run $fileici ......" >> $LOG
echo "===================" >> $LOG
cp $IGVPT2BIN .
cp $DEFAULTDIR/*.gab .
cp $DEFAULTDIR/*.out .
time ./cchemi $fileici >>  $LOG
echo "======================"
cp *gab $DEFAULTDIR/.
cd 
/bin/rm -r $IGVPT2TMP
