#!/bin/bash

export IGVPT2DIR=$HOME/iGVPT2
export PATH=$IGVPT2DIR/bin:$PATH
export PATH=$IGVPT2DIR/shell:$PATH
export LD_LIBRARY_PATH=$IGVPT2DIR/lib:$LD_LIBRARY_PATH

fname="step3"
echo " Begin QFF3MR-VPT2 calculation">  $fname.log


# make ici  file for VPT2 calculation
echo 'RunType=VPT2' > CH2F2QFF.ici
cat CH2F2QFF.txt >> CH2F2QFF.ici

# generate txt data for VPT2 calculation
igvpt2 CH2F2QFF.ici  >  $fname.out 2>> $fname.err

echo "==========================================================================="
echo "See $fname.out , $fname.log and $fname.err files "
echo "==========================================================================="
